### ISSUE TITLE
windows版本的能发布一个吗

### ISSUE THREAD

**Issue by caffeTao** [sailorsb/caffe-parallel#2]
对于许多初学者来说，使用windows下面的vs开发还是要方便许多，python wrapper、matlab wrapper都可以使得使用更加人性化和便携性，不知道贵公司能不能做一个

**Comment by huangfeidian** [comment]
The caffe-parallel relys on pthread.h besides the original caffe. It's not practical to introduce pthread.h/hdf5.h/glogs.h etc to windows. The original caffe version doesn't fit windows well.

**Comment by caffeTao** [comment]
caffe的这几个依赖库都有人在windows下进行编译了，在convnet的windows编译 中，也有类似的已编译好的库，需要的话我发给你们参考下，您看，可以吗
