### ISSUE TITLE
ERROR when "mpiexec -n 1 xxxxxx"

### ISSUE THREAD

**Issue by wuyuebupt** [sailorsb/caffe-parallel#5]
hi, I run the program successfully with the configuration "-n 2" with 2 k40.
However, the program gets stuck when I use "-n 1".

The example I use is MNIST.

Details are below:
I0611 23:32:33.560036 25939 caffe.cpp:107] Use GPU with device ID 0
I0611 23:32:53.725818 25939 caffe.cpp:115] Starting Optimization
I0611 23:32:53.869191 25939 solver.cpp:223] Initializing solver from parameters: 
test_iter: 100
test_interval: 500
base_lr: 0.01
display: 100
max_iter: 10000
lr_policy: "inv"
gamma: 0.0001
power: 0.75
momentum: 0.9
weight_decay: 0.0005
snapshot: 5000
snapshot_prefix: "examples/mnist/lenet"
solver_mode: GPU
net: "examples/mnist/lenet_train_test.prototxt"
I0611 23:32:53.933658 25939 solver.cpp:271] Creating training net from net file: examples/mnist/lenet_train_test.prototxt
I0611 23:32:54.124568 25939 net.cpp:277] The NetState phase (0) differed from the phase (1) specified by a rule in layer mnist
I0611 23:32:54.124601 25939 net.cpp:277] The NetState phase (0) differed from the phase (1) specified by a rule in layer accuracy
I0611 23:32:54.124693 25939 net.cpp:40] Initializing net from parameters: 
name: "LeNet"
layers {
  top: "data"
  top: "label"
  name: "mnist"
  type: DATA
  data_param {
    source: "examples/mnist/mnist_train_lmdb"
    batch_size: 64
    backend: LMDB
  }
  include {
    phase: TRAIN
  }
  transform_param {
    scale: 0.00390625
  }
}
layers {
  bottom: "data"
  top: "conv1"
  name: "conv1"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "conv1"
  top: "pool1"
  name: "pool1"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layers {
  bottom: "pool1"
  top: "conv2"
  name: "conv2"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  convolution_param {
    num_output: 50
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "conv2"
  top: "pool2"
  name: "pool2"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layers {
  bottom: "pool2"
  top: "ip1"
  name: "ip1"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "ip1"
  top: "ip1"
  name: "relu1"
  type: RELU
}
layers {
  bottom: "ip1"
  top: "ip2"
  name: "ip2"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  inner_product_param {
    num_output: 10
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "ip2"
  bottom: "label"
  top: "loss"
  name: "loss"
  type: SOFTMAX_LOSS
}
state {
  phase: TRAIN
}
I0611 23:32:54.124752 25939 net.cpp:69] Creating Layer mnist
I0611 23:32:54.124758 25939 net.cpp:358] mnist -> data
I0611 23:32:54.124773 25939 net.cpp:358] mnist -> label
I0611 23:32:54.191617 25939 net.cpp:98] Setting up mnist
I0611 23:32:55.070849 25939 data_layer.cpp:80] Opening lmdb examples/mnist/mnist_train_lmdb
I0611 23:32:55.151121 25939 data_layer.cpp:162] output data size: 64,1,28,28
I0611 23:32:55.151221 25939 net.cpp:105] Top shape: 64 1 28 28 (50176)
I0611 23:32:55.151226 25939 net.cpp:105] Top shape: 64 1 1 1 (64)
I0611 23:32:55.151239 25939 net.cpp:69] Creating Layer conv1
I0611 23:32:55.151242 25939 net.cpp:396] conv1 <- data
I0611 23:32:55.151259 25939 net.cpp:358] conv1 -> conv1
I0611 23:32:55.151267 25939 net.cpp:98] Setting up conv1
I0611 23:32:55.151628 25939 net.cpp:105] Top shape: 64 20 24 24 (737280)
I0611 23:32:55.151664 25939 net.cpp:69] Creating Layer pool1
I0611 23:32:55.151667 25939 net.cpp:396] pool1 <- conv1
I0611 23:32:55.151671 25939 net.cpp:358] pool1 -> pool1
I0611 23:32:55.151676 25939 net.cpp:98] Setting up pool1
I0611 23:32:55.151686 25939 net.cpp:105] Top shape: 64 20 12 12 (184320)
I0611 23:32:55.151692 25939 net.cpp:69] Creating Layer conv2
I0611 23:32:55.151695 25939 net.cpp:396] conv2 <- pool1
I0611 23:32:55.151698 25939 net.cpp:358] conv2 -> conv2
I0611 23:32:55.151702 25939 net.cpp:98] Setting up conv2
I0611 23:32:55.151856 25939 net.cpp:105] Top shape: 64 50 8 8 (204800)
I0611 23:32:55.151883 25939 net.cpp:69] Creating Layer pool2
I0611 23:32:55.151886 25939 net.cpp:396] pool2 <- conv2
I0611 23:32:55.151890 25939 net.cpp:358] pool2 -> pool2
I0611 23:32:55.151895 25939 net.cpp:98] Setting up pool2
I0611 23:32:55.151897 25939 net.cpp:105] Top shape: 64 50 4 4 (51200)
I0611 23:32:55.151901 25939 net.cpp:69] Creating Layer ip1
I0611 23:32:55.151903 25939 net.cpp:396] ip1 <- pool2
I0611 23:32:55.151907 25939 net.cpp:358] ip1 -> ip1
I0611 23:32:55.151911 25939 net.cpp:98] Setting up ip1
I0611 23:32:55.154345 25939 net.cpp:105] Top shape: 64 500 1 1 (32000)
I0611 23:32:55.154355 25939 net.cpp:69] Creating Layer relu1
I0611 23:32:55.154357 25939 net.cpp:396] relu1 <- ip1
I0611 23:32:55.154361 25939 net.cpp:347] relu1 -> ip1 (in-place)
I0611 23:32:55.154366 25939 net.cpp:98] Setting up relu1
I0611 23:32:55.154367 25939 net.cpp:105] Top shape: 64 500 1 1 (32000)
I0611 23:32:55.154371 25939 net.cpp:69] Creating Layer ip2
I0611 23:32:55.154373 25939 net.cpp:396] ip2 <- ip1
I0611 23:32:55.154377 25939 net.cpp:358] ip2 -> ip2
I0611 23:32:55.154381 25939 net.cpp:98] Setting up ip2
I0611 23:32:55.154414 25939 net.cpp:105] Top shape: 64 10 1 1 (640)
I0611 23:32:55.154422 25939 net.cpp:69] Creating Layer loss
I0611 23:32:55.154424 25939 net.cpp:396] loss <- ip2
I0611 23:32:55.154428 25939 net.cpp:396] loss <- label
I0611 23:32:55.154431 25939 net.cpp:358] loss -> loss
I0611 23:32:55.154438 25939 net.cpp:98] Setting up loss
I0611 23:32:55.154443 25939 net.cpp:105] Top shape: 1 1 1 1 (1)
I0611 23:32:55.154446 25939 net.cpp:111]     with loss weight 1
I0611 23:32:55.154475 25939 net.cpp:172] loss needs backward computation.
I0611 23:32:55.154479 25939 net.cpp:172] ip2 needs backward computation.
I0611 23:32:55.154480 25939 net.cpp:172] relu1 needs backward computation.
I0611 23:32:55.154484 25939 net.cpp:172] ip1 needs backward computation.
I0611 23:32:55.154485 25939 net.cpp:172] pool2 needs backward computation.
I0611 23:32:55.154487 25939 net.cpp:172] conv2 needs backward computation.
I0611 23:32:55.154489 25939 net.cpp:172] pool1 needs backward computation.
I0611 23:32:55.154492 25939 net.cpp:172] conv1 needs backward computation.
I0611 23:32:55.154495 25939 net.cpp:174] mnist does not need backward computation.
I0611 23:32:55.154496 25939 net.cpp:210] This network produces output loss
I0611 23:32:55.154507 25939 net.cpp:469] Collecting Learning Rate and Weight Decay.
I0611 23:32:55.154512 25939 net.cpp:221] Network initialization done.
I0611 23:32:55.154515 25939 net.cpp:222] Memory required for data: 5169924
I0611 23:32:55.154808 25939 solver.cpp:355] Creating test net (#0) specified by net file: examples/mnist/lenet_train_test.prototxt
I0611 23:32:55.154839 25939 net.cpp:277] The NetState phase (1) differed from the phase (0) specified by a rule in layer mnist
I0611 23:32:55.154935 25939 net.cpp:40] Initializing net from parameters: 
name: "LeNet"
layers {
  top: "data"
  top: "label"
  name: "mnist"
  type: DATA
  data_param {
    source: "examples/mnist/mnist_test_lmdb"
    batch_size: 100
    backend: LMDB
  }
  include {
    phase: TEST
  }
  transform_param {
    scale: 0.00390625
  }
}
layers {
  bottom: "data"
  top: "conv1"
  name: "conv1"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "conv1"
  top: "pool1"
  name: "pool1"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layers {
  bottom: "pool1"
  top: "conv2"
  name: "conv2"
  type: CONVOLUTION
  blobs_lr: 1
  blobs_lr: 2
  convolution_param {
    num_output: 50
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "conv2"
  top: "pool2"
  name: "pool2"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layers {
  bottom: "pool2"
  top: "ip1"
  name: "ip1"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "ip1"
  top: "ip1"
  name: "relu1"
  type: RELU
}
layers {
  bottom: "ip1"
  top: "ip2"
  name: "ip2"
  type: INNER_PRODUCT
  blobs_lr: 1
  blobs_lr: 2
  inner_product_param {
    num_output: 10
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layers {
  bottom: "ip2"
  bottom: "label"
  top: "accuracy"
  name: "accuracy"
  type: ACCURACY
  include {
    phase: TEST
  }
}
layers {
  bottom: "ip2"
  bottom: "label"
  top: "loss"
  name: "loss"
  type: SOFTMAX_LOSS
}
state {
  phase: TEST
}
I0611 23:32:55.154999 25939 net.cpp:69] Creating Layer mnist
I0611 23:32:55.155004 25939 net.cpp:358] mnist -> data
I0611 23:32:55.155009 25939 net.cpp:358] mnist -> label
I0611 23:32:55.155014 25939 net.cpp:98] Setting up mnist
I0611 23:32:55.860347 25939 data_layer.cpp:80] Opening lmdb examples/mnist/mnist_test_lmdb
I0611 23:32:55.933403 25939 data_layer.cpp:162] output data size: 100,1,28,28
I0611 23:32:55.933531 25939 net.cpp:105] Top shape: 100 1 28 28 (78400)
I0611 23:32:55.933539 25939 net.cpp:105] Top shape: 100 1 1 1 (100)
I0611 23:32:55.933552 25939 net.cpp:69] Creating Layer label_mnist_1_split
I0611 23:32:55.933557 25939 net.cpp:396] label_mnist_1_split <- label
I0611 23:32:55.933563 25939 net.cpp:358] label_mnist_1_split -> label_mnist_1_split_0
I0611 23:32:55.933573 25939 net.cpp:358] label_mnist_1_split -> label_mnist_1_split_1
I0611 23:32:55.933578 25939 net.cpp:98] Setting up label_mnist_1_split
I0611 23:32:55.933584 25939 net.cpp:105] Top shape: 100 1 1 1 (100)
I0611 23:32:55.933588 25939 net.cpp:105] Top shape: 100 1 1 1 (100)
I0611 23:32:55.933596 25939 net.cpp:69] Creating Layer conv1
I0611 23:32:55.933601 25939 net.cpp:396] conv1 <- data
I0611 23:32:55.933606 25939 net.cpp:358] conv1 -> conv1
I0611 23:32:55.933612 25939 net.cpp:98] Setting up conv1
I0611 23:32:55.933632 25939 net.cpp:105] Top shape: 100 20 24 24 (1152000)
I0611 23:32:55.933645 25939 net.cpp:69] Creating Layer pool1
I0611 23:32:55.933648 25939 net.cpp:396] pool1 <- conv1
I0611 23:32:55.933655 25939 net.cpp:358] pool1 -> pool1
I0611 23:32:55.933660 25939 net.cpp:98] Setting up pool1
I0611 23:32:55.933665 25939 net.cpp:105] Top shape: 100 20 12 12 (288000)
I0611 23:32:55.933672 25939 net.cpp:69] Creating Layer conv2
I0611 23:32:55.933676 25939 net.cpp:396] conv2 <- pool1
I0611 23:32:55.933682 25939 net.cpp:358] conv2 -> conv2
I0611 23:32:55.933687 25939 net.cpp:98] Setting up conv2
I0611 23:32:55.933881 25939 net.cpp:105] Top shape: 100 50 8 8 (320000)
I0611 23:32:55.933893 25939 net.cpp:69] Creating Layer pool2
I0611 23:32:55.933897 25939 net.cpp:396] pool2 <- conv2
I0611 23:32:55.933902 25939 net.cpp:358] pool2 -> pool2
I0611 23:32:55.933907 25939 net.cpp:98] Setting up pool2
I0611 23:32:55.933912 25939 net.cpp:105] Top shape: 100 50 4 4 (80000)
I0611 23:32:55.933918 25939 net.cpp:69] Creating Layer ip1
I0611 23:32:55.933923 25939 net.cpp:396] ip1 <- pool2
I0611 23:32:55.933928 25939 net.cpp:358] ip1 -> ip1
I0611 23:32:55.933935 25939 net.cpp:98] Setting up ip1
I0611 23:32:55.937114 25939 net.cpp:105] Top shape: 100 500 1 1 (50000)
I0611 23:32:55.937126 25939 net.cpp:69] Creating Layer relu1
I0611 23:32:55.937130 25939 net.cpp:396] relu1 <- ip1
I0611 23:32:55.937135 25939 net.cpp:347] relu1 -> ip1 (in-place)
I0611 23:32:55.937140 25939 net.cpp:98] Setting up relu1
I0611 23:32:55.937144 25939 net.cpp:105] Top shape: 100 500 1 1 (50000)
I0611 23:32:55.937152 25939 net.cpp:69] Creating Layer ip2
I0611 23:32:55.937156 25939 net.cpp:396] ip2 <- ip1
I0611 23:32:55.937161 25939 net.cpp:358] ip2 -> ip2
I0611 23:32:55.937167 25939 net.cpp:98] Setting up ip2
I0611 23:32:55.937238 25939 net.cpp:105] Top shape: 100 10 1 1 (1000)
I0611 23:32:55.937245 25939 net.cpp:69] Creating Layer ip2_ip2_0_split
I0611 23:32:55.937249 25939 net.cpp:396] ip2_ip2_0_split <- ip2
I0611 23:32:55.937258 25939 net.cpp:358] ip2_ip2_0_split -> ip2_ip2_0_split_0
I0611 23:32:55.937283 25939 net.cpp:358] ip2_ip2_0_split -> ip2_ip2_0_split_1
I0611 23:32:55.937288 25939 net.cpp:98] Setting up ip2_ip2_0_split
I0611 23:32:55.937293 25939 net.cpp:105] Top shape: 100 10 1 1 (1000)
I0611 23:32:55.937296 25939 net.cpp:105] Top shape: 100 10 1 1 (1000)
I0611 23:32:55.937304 25939 net.cpp:69] Creating Layer accuracy
I0611 23:32:55.937307 25939 net.cpp:396] accuracy <- ip2_ip2_0_split_0
I0611 23:32:55.937312 25939 net.cpp:396] accuracy <- label_mnist_1_split_0
I0611 23:32:55.937317 25939 net.cpp:358] accuracy -> accuracy
I0611 23:32:55.937324 25939 net.cpp:98] Setting up accuracy
I0611 23:32:55.937327 25939 net.cpp:105] Top shape: 1 1 1 1 (1)
I0611 23:32:55.937333 25939 net.cpp:69] Creating Layer loss
I0611 23:32:55.937337 25939 net.cpp:396] loss <- ip2_ip2_0_split_1
I0611 23:32:55.937341 25939 net.cpp:396] loss <- label_mnist_1_split_1
I0611 23:32:55.937346 25939 net.cpp:358] loss -> loss
I0611 23:32:55.937351 25939 net.cpp:98] Setting up loss
I0611 23:32:55.937358 25939 net.cpp:105] Top shape: 1 1 1 1 (1)
I0611 23:32:55.937362 25939 net.cpp:111]     with loss weight 1
I0611 23:32:55.937372 25939 net.cpp:172] loss needs backward computation.
I0611 23:32:55.937376 25939 net.cpp:174] accuracy does not need backward computation.
I0611 23:32:55.937381 25939 net.cpp:172] ip2_ip2_0_split needs backward computation.
I0611 23:32:55.937384 25939 net.cpp:172] ip2 needs backward computation.
I0611 23:32:55.937387 25939 net.cpp:172] relu1 needs backward computation.
I0611 23:32:55.937391 25939 net.cpp:172] ip1 needs backward computation.
I0611 23:32:55.937396 25939 net.cpp:172] pool2 needs backward computation.
I0611 23:32:55.937398 25939 net.cpp:172] conv2 needs backward computation.
I0611 23:32:55.937402 25939 net.cpp:172] pool1 needs backward computation.
I0611 23:32:55.937407 25939 net.cpp:172] conv1 needs backward computation.
I0611 23:32:55.937410 25939 net.cpp:174] label_mnist_1_split does not need backward computation.
I0611 23:32:55.937414 25939 net.cpp:174] mnist does not need backward computation.
I0611 23:32:55.937417 25939 net.cpp:210] This network produces output accuracy
I0611 23:32:55.937422 25939 net.cpp:210] This network produces output loss
I0611 23:32:55.937433 25939 net.cpp:469] Collecting Learning Rate and Weight Decay.
I0611 23:32:55.937439 25939 net.cpp:221] Network initialization done.
I0611 23:32:55.937443 25939 net.cpp:222] Memory required for data: 8086808
I0611 23:32:55.937486 25939 solver.cpp:245] Solver scaffolding done.
I0611 23:32:55.937494 25939 solver.cpp:364] Solving LeNet

**Comment by MdAsifKhan** [comment]
If you are using single GPU your process number should be 2. As for 'm'
GPUs the process number should be 'm+1'.
ᐧ

Thanks & Regards,
M. Asif Khan | Undergraduate Final Year Student
Electronics & Communication Engineering
The LNM Institute of Information Technology
Jaipur-302 031,India
Mb: +91-9413259815

   -
      -
         -
            - in.linkedin.com/pub/mohammad-asif-khan/56/540/803/"Knowledge
            is the eye of desire and can become the pilot of the soul"
-Will Durant

**Comment by MdAsifKhan** [comment]
If you are using single GPU your process number should be 2. As for 'm' GPUs the process number should be 'm+1'.

**Comment by wuyuebupt** [comment]
@MdAsifKhan Thanks.
You are right.
It utilizes additional memory in the first card to synchronize.
